[package]
name = "caramel-potatoe-cat"
version = "0.1.0"
authors = [
    "Mark W. Murphy <murphy.mark.w+github@gmail.com>",
]

[dependencies]
env_logger = "*"
log = "*"
nom = "*"

[dependencies.clap]
version = ">2.23.0"
features = ["yaml", "color"]
